### ISSUE TITLE
Error Connection Timedout on first ssh connection with Android

### ISSUE THREAD

**Issue by mat-his** [jda258/flutter_ssh#11]
I want to SSH connect to my personal local server with my Android smartphone. 

The SSH connection on my linux computer as a client is working fine, but when I try to connect with the flutter ssh2 plugin, it gives me these errors: 

`E/SshPlugin(18764): Connection failed: java.net.ConnectException: failed to connect to /192.168.1.17 (port 22) from /:: (port 49702): connect failed: ETIMEDOUT (Connection timed out)
E/flutter (18764): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(connection_failure, java.net.ConnectException: failed to connect to /192.168.1.17 (port 22) from /:: (port 49702): connect failed: ETIMEDOUT (Connection timed out), null, null)
E/flutter (18764): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (18764): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (18764): <asynchronous suspension>
E/flutter (18764): #2      SSHClient.connect (package:ssh2/ssh2.dart:101:18)
E/flutter (18764): <asynchronous suspension>
E/flutter (18764): #3      SshState.initSsh (package:myapp/src/views/ui/tools/sshClass.dart:34:14)
E/flutter (18764): <asynchronous suspension>
E/flutter (18764): `

I know it is the first SSH connection with this device on my local server. Should I accept a fingerprint key ? if so, how ?

Thanks for your help

**Comment by jda258** [comment]
You say it times out on the first connection, but does it also time out on subsequent ones? What do you see in the sshd logs on your server?

**Comment by mat-his** [comment]
I tried to connect again to retrieve the logs, when I realised that I had kept my VPN active. In short I was not on the local network, beginner's mistake sorry.

The problem is now solved.
