### ISSUE TITLE
Project doesn't build Execution failed for task ':ssh2:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by laura-rodriguez8** [jda258/flutter_ssh#12]
Hi 
Hope you can help me with my problem I am very new to flutter, also I apologize if it's difficult to understand me since english isn't my first laguage.

I want to develop an app using ssh protocol. I download the whole code file of ssh2 package and try to run the example code, builds and works prefectly, then I try to implemented to my project, click Run and get the next error

```
Note: C:\scr\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_android-2.0.9\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ssh2:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':ssh2:debugCompileClasspath'.
   > Failed to transform bcprov-jdk15on-1.69.jar (org.bouncycastle:bcprov-jdk15on:1.69) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for JetifyTransform: C:\Users\laura\.gradle\caches\modules-2\files-2.1\org.bouncycastle\bcprov-jdk15on\1.69\91e1628251cf3ca90093ce9d0fe67e5b7dab3850\bcprov-jdk15on-1.69.jar.
         > Failed to transform 'C:\Users\laura\.gradle\caches\modules-2\files-2.1\org.bouncycastle\bcprov-jdk15on\1.69\91e1628251cf3ca90093ce9d0fe67e5b7dab3850\bcprov-jdk15on-1.69.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 59. (Run with --stacktrace for more details.)
           Suggestions:
            - Check out existing issues at https://issuetracker.google.com/issues?q=componentid:460323&s=modified_time:desc, it's possible that this issue has already been filed there.
            - If this issue has not been filed, please report it at https://issuetracker.google.com/issues/new?component=460323 (run with --stacktrace and provide a stack trace if possible).
   > Failed to transform jsch-0.1.66.jar (com.github.mwiede:jsch:0.1.66) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for JetifyTransform: C:\Users\laura\.gradle\caches\modules-2\files-2.1\com.github.mwiede\jsch\0.1.66\dace8dd51ea58220b9b5e2a6dd2c453a2925ae93\jsch-0.1.66.jar.
         > Failed to transform 'C:\Users\laura\.gradle\caches\modules-2\files-2.1\com.github.mwiede\jsch\0.1.66\dace8dd51ea58220b9b5e2a6dd2c453a2925ae93\jsch-0.1.66.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 60. (Run with --stacktrace for more details.)
           Suggestions:
            - Check out existing issues at https://issuetracker.google.com/issues?q=componentid:460323&s=modified_time:desc, it's possible that this issue has already been filed there.
            - If this issue has not been filed, please report it at https://issuetracker.google.com/issues/new?component=460323 (run with --stacktrace and provide a stack trace if possible).

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 24s
Exception: Gradle task assembleDebug failed with exit code 1
```

This is my android\build.gradle

```
buildscript {
    ext.kotlin_version = '1.4.32'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

````
This is my android/app/build.gradle

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new FileNotFoundException()("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion flutter.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.untitled5"
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

````
This is my pubspec.yaml

```
name: untitled5
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.16.0-35.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  ssh2: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  path_provider: ^2.0.1
 
  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true
```
I don't understand what I am doing wrong.

I'd appreciate if you could guide me on the implementation of the package to solve this error

**Comment by ghost** [comment]
FYI I have the same issue. Haven't found any solution so far. I keep searching.

**Comment by ghost** [comment]
@laura-rodriguez8

As written here https://pub.dev/documentation/ssh2/latest/, the lib was tested with gradle 7.0.2:

![image](https://user-images.githubusercontent.com/64216540/144778989-02c50313-1001-42fe-bb09-09d03ec5fe05.png)

Try to build your app with this version.

**Comment by ghost** [comment]
Okay, I found a solution that worked for me:

#### 1) upgraded JDK to JDK 15 (I am not sure it had an effect)



Then, based on this issue https://github.com/mwiede/jsch/issues/41:

#### 2) upgraded Gradle to 7.0.2 as follows:

In file *android > gradle > wrapper > gradle-wrapper.properties* I replaced:
- `distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip`
- with `distributionUrl=https\://services.gradle.org/distributions/gradle-7.0.2-all.zip`

####  3) upgraded the Gradle build tool as follows:

In file *android > build.gradle* I replaced:
- `com.android.tools.build:gradle:4.2.2` 
-  with `com.android.tools.build:gradle:7.0.2`

**Comment by jda258** [comment]
Thanks for answering this @raspibuddy. Did this work for you @laura-rodriguez8? I've found the easiest way to upgrade Gradle is with Android Studio.

**Comment by catonzio** [comment]
> Okay, I found a solution that worked for me:
> 
> #### 1) upgraded JDK to JDK 15 (I am not sure it had an effect)
> Then, based on this issue [mwiede/jsch#41](https://github.com/mwiede/jsch/issues/41):
> 
> #### 2) upgraded Gradle to 7.0.2 as follows:
> In file _android > gradle > wrapper > gradle-wrapper.properties_ I replaced:
> 
> * `distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip`
> * with `distributionUrl=https\://services.gradle.org/distributions/gradle-7.0.2-all.zip`
> 
> #### 3) upgraded the Gradle build tool as follows:
> In file _android > build.gradle_ I replaced:
> 
> * `com.android.tools.build:gradle:4.2.2`
> * with `com.android.tools.build:gradle:7.0.2`

Hello, even if I changed the gradle version it didn't work.
It firstly says that jlink was missing, but now it says that jmod is missing. I think I miss some dependencies/packages.

> FAILURE: Build failed with an exception.
> What went wrong:
> Execution failed for task ':ssh2:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':ssh2:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: /opt/Android/Sdk/platforms/android-30/core-for-system-modules.jar.
         > jmod executable /home/catonz/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085/jre/bin/jmod does not exist.

The exception for JLink was the same, except that it was "jlink" instead of "jmod". Do you know how to solve the issue?

**Comment by ghost** [comment]
@Catonzio 

I don't know how to solve your issue.

My suggestions:

1) I would search along those lines:
- https://stackoverflow.com/a/67659034/6111549
- https://github.com/flutter/flutter/issues/56778#issuecomment-742639036
As @jda258 said, using AndroidStudio to fix this kind of issue seems to be helpful.

2) Otherwise, I would also look into re-installing or upgrading Java.

**Comment by catonzio** [comment]
Luckily I managed to solve the problem.
I have Ubuntu 20.04.

- First of all, I have installed and upgraded Gradle following this guide: [https://medium.com/@gtxgat/upgrade-gradle-version-professionally-in-flutter-5e0c16305cc0](url)

- Then, I made a symbolic link of jlink and jmod to `~/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085/jre/bin` from `/usr/bin` with the command `ln -s /usr/bin/jre/jlink ~/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085/jre/bin` and the same for jmod.

After this steps, everything worked fine; maybe the problem was that in the AndroidStudio folder there weren't jmod and jlink, causing issues.

**Comment by raphasauer** [comment]
> 1) upgraded JDK to JDK 15 (I am not sure it had an effect)

I can confirm this step is important. My project was failing to build until I downgraded my JDK (from 19 to 15).
