### ISSUE TITLE
Unable to Login after connecting ssh connection.

### ISSUE THREAD

**Issue by sitakanta136** [jda258/flutter_ssh#17]
When I try to log in after an ssh connection => Unbale to login and throws blow Error.
Unhandled Exception: SocketException: Connection failed (OS Error: Machine is not on the network, errno = 64), address = login.parker.com, port = 443

I observed InternetAdrress change IPV4 to IPV6.

**Comment by jda258** [comment]
I'd expect this behavior if your local connection changes. An SSH session is a stateful connection and will break if you switch IP addresses.
